"""Alembic environment configuration.

Reads DATABASE_URL from job_assist.config.Settings (which loads from
the DATABASE_URL environment variable or apps/api/.env).

The DATABASE_URL must use the *sync* psycopg2 driver for Alembic:
  postgresql://user:pass@host:port/dbname

If the env var is set to the asyncpg runtime URL
(postgresql+asyncpg://...), the +asyncpg portion is stripped
automatically so the same variable can serve both Alembic and the app.

pgvector support: Vector columns are rendered correctly in autogenerated
migration files via the render_item hook.
"""

from __future__ import annotations

from logging.config import fileConfig
from typing import Any

from alembic import context
from pgvector.sqlalchemy import Vector
from sqlalchemy import engine_from_config, pool

from job_assist.config import settings
from job_assist.db.base import Base

# ---------------------------------------------------------------------------
# Alembic Config object — gives access to values in alembic.ini.
# ---------------------------------------------------------------------------
config = context.config

# Attach Python logging config from alembic.ini.
if config.config_file_name is not None:
    fileConfig(config.config_file_name)

# ---------------------------------------------------------------------------
# Resolve a *sync* database URL for Alembic.
# Strip +asyncpg (or any other async dialect suffix) if present.
# ---------------------------------------------------------------------------
_raw_url: str = settings.database_url
_sync_url: str = _raw_url.replace("postgresql+asyncpg://", "postgresql://").replace(
    "postgresql+aiosqlite://", "sqlite:///"
)
config.set_main_option("sqlalchemy.url", _sync_url)

# ---------------------------------------------------------------------------
# target_metadata: points to all ORM models so autogenerate works.
# Models are registered automatically when imported; add new model
# modules to job_assist/db/__init__.py as they are created in Week 1+.
# ---------------------------------------------------------------------------
target_metadata = Base.metadata


# ---------------------------------------------------------------------------
# pgvector autogenerate support
# ---------------------------------------------------------------------------
def render_item(type_: str, obj: Any, autogen_context: Any) -> str | bool:
    """Render pgvector Vector columns in autogenerated migration files."""
    if type_ == "type" and isinstance(obj, Vector):
        autogen_context.imports.add("from pgvector.sqlalchemy import Vector")
        if obj.dim is not None:
            return f"Vector({obj.dim})"
        return "Vector()"
    # Return False to fall back to Alembic's default rendering.
    return False


# ---------------------------------------------------------------------------
# Migration runners
# ---------------------------------------------------------------------------
def run_migrations_offline() -> None:
    """Run migrations in 'offline' mode (no live DB connection).

    Emits SQL to stdout.  Useful for reviewing what would be applied.
    """
    url = config.get_main_option("sqlalchemy.url")
    context.configure(
        url=url,
        target_metadata=target_metadata,
        literal_binds=True,
        dialect_opts={"paramstyle": "named"},
        render_item=render_item,
    )

    with context.begin_transaction():
        context.run_migrations()


def run_migrations_online() -> None:
    """Run migrations in 'online' mode (live DB connection)."""
    connectable = engine_from_config(
        config.get_section(config.config_ini_section, {}),
        prefix="sqlalchemy.",
        poolclass=pool.NullPool,
    )

    with connectable.connect() as connection:
        context.configure(
            connection=connection,
            target_metadata=target_metadata,
            render_item=render_item,
        )

        with context.begin_transaction():
            context.run_migrations()


if context.is_offline_mode():
    run_migrations_offline()
else:
    run_migrations_online()
